name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: steps-repro
    attributes:
      label: Steps to reproduce the issue?
      description: These are the steps that we can use to recreate the issue on our devices.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your environment (if applicable)
      description: Run `npx envinfo --system --duplicates --npmPackages` in the Catalyst repo (only if it relates to internal files or OS)
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Catalyst are you running?
    validations:
      required: true
