name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: <title>"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature Request!
  - type: textarea
    id: is-related
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you would like!
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: alts
    attributes:
      label: Describe alternatives you have considered.
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
